# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_completado_task_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deletion_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
