name: Deploy Django to Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /opt/bitnami/projects/django-youragenda
          git pull origin master
          /opt/bitnami/python/bin/pip install -r requirements.txt
          /opt/bitnami/python/bin/python manage.py migrate
          /opt/bitnami/python/bin/python manage.py collectstatic --noinput
          sudo /opt/bitnami/ctlscript.sh restart apache